### ISSUE TITLE
Duplicate URLs are wrong

### ISSUE THREAD

**Issue by kolaente** [elgentos/regenerate-catalog-urls#10]
When regenerating URLs for duplicate categories, it throws an error like this:
```
Duplicated url for store ID 0, category 1278 (Sale & Auslaufartikel) - URL key for specified store already exists. Generated URLs:
sale-auslaufartikel/_1
```
Shouldn't this duplicate URL be `sale-auslaufartikel_1` instead of `sale-auslaufartikel/_1`?

**Comment by peterjaap** [comment]
Hard to say without knowing the categories. It looks like its creating a subcategory with the slug `_1`. I guess you're referring to the way Magento handles duplicate URLs by adding a counter at the end, but in that case it would be a dash (`-`) instead of an underscore before the number.

**Comment by kolaente** [comment]
We have two categories with the same name and the same url (`Sale & Auslaufartikel`) in our db. It generates the URL for the first category and the throws the error above and doesn't put the url it said it generated (`sale-auslaufartikel/_1`) into the database.

It seems like this url gets generated somewhere in `Console/Command/RegenerateCategoryUrlCommand.php:185`.

**Comment by peterjaap** [comment]
Well the only thing this extension does is *trigger* the regeneration, not actually regenerate the URLs. That's Magento's responsibility so I think you should look a bit deeper for the true cause.

**Comment by peterjaap** [comment]
Closing for now.
