### ISSUE TITLE
it generate double .html 

### ISSUE THREAD

**Issue by to8gal** [elgentos/regenerate-catalog-urls#16]
at the end of the url, where I actually do not want any extension is generated a double html, like this

.html.html

**Comment by peterjaap** [comment]
Are you sure this doesn't happen with default Magento as well? This extension basically only triggers the generation, it does not handle the generation itself.

**Comment by to8gal** [comment]
Yes I am sure the double html was not there before,
Now I dunno how to get back to original url

**Comment by to8gal** [comment]
I actually disabled your module and installed another, and manage to get back on track
But thanks

**Comment by peterjaap** [comment]
That's surprising. Which one did you try so I can check for any differences?

**Comment by to8gal** [comment]
They are not the best, cause I cannot get to the result I want which is product /name/sku/ but they work quite good

olegkoval/magento2-regenerate_url_rewrites
staempfli/magento2-module-rebuild-url-rewrite

The first one is the one I am using right now, pretty coherent results

**Comment by peterjaap** [comment]
Closed due to inactivity.
