### ISSUE TITLE
[BUG] Use proxy in constructor

### ISSUE THREAD

**Issue by wouter-toppershops** [elgentos/regenerate-catalog-urls#18]
During the install of an clean magento installation. it loops through the commands.

you use o.a.t. ProductCollection which uses Config at his time, which uses Storemanager at his time. 

this will throw an error about store not found and even store table not excists. which makes sence because you try to install magento. 

the sollution to this is, using Proxies in Magento. (https://devdocs.magento.com/guides/v2.0/extension-dev-guide/proxies.html)

**Comment by wouter-toppershops** [comment]
See Issue https://github.com/elgentos/regenerate-catalog-urls/pull/19

**Comment by peterjaap** [comment]
Super, thanks! :+1:

**Comment by riconeitzel** [comment]
shouldn't these proxies be used in the CMS command as well?!

**Comment by peterjaap** [comment]
Yes they should. Fixed; https://github.com/elgentos/regenerate-catalog-urls/commit/252906b0b0a3723de3b0fdb49a56dd72ba0dba79

**Comment by peterjaap** [comment]
Created [0.2.6](https://github.com/elgentos/regenerate-catalog-urls/releases/tag/0.2.6)
