### ISSUE TITLE
Root category url causes redirect loop

### ISSUE THREAD

**Issue by ctadlock** [elgentos/regenerate-catalog-urls#20]
![image](https://user-images.githubusercontent.com/1539397/49166862-0fbac400-f2e9-11e8-85aa-29e11044c050.png)

What is the purpose of this rewrite? I have to delete the row, otherwise a request to the home page of my store causes an infinite redirect loop.

**Comment by ctadlock** [comment]
The same bug was reported here: https://github.com/experius/Magento2-Module-Experius-ReindexCatalogUrlRewrites/issues/10

**Comment by peterjaap** [comment]
Please report the bug in the magento/magento2 repo. The reason why this happens in this extension and in the one you mention is because it's not in the extension. These extensions only *trigger* generation of the rewrite URL's, it doesn't make the actual rewrites, Magento does.

**Comment by peterjaap** [comment]
@ctadlock sorry to have jumped the gun by blaming Magento back in November. I just ran into this myself and it turns out you're right. I now added a level filter to skip the root categories when letting Magento generate the URLs; https://github.com/elgentos/regenerate-catalog-urls/commit/6a31dc88c8eba00bca1bdea7f0310283d02d792c

Again, sorry to have dismissed your comment so easily.

**Comment by gototagsdev** [comment]
@peterjaap This doesnt seem to have resolved the issue. My category `id:2` is `Default Category`; its parent `id:1` is `Root Category`.

Is this a multi-store issue? I have two websites; one for USA and one for Canada.

I have to run this sql to remove the record that causes the home page redirect.
```
DELETE FROM `url_rewrite` WHERE `entity_type` = 'category' AND `request_path` = '/';
```

`url_rewite`...

![image](https://user-images.githubusercontent.com/2015303/68811350-4c301e80-0625-11ea-85d6-df6e5d337212.png)


`catalog_category_entity`...

![image](https://user-images.githubusercontent.com/2015303/68811736-2eaf8480-0626-11ea-99bd-e50951b24c5d.png)

`admin`...

![image](https://user-images.githubusercontent.com/2015303/68811768-3ec76400-0626-11ea-8188-96b57da27252.png)

**Comment by peterjaap** [comment]
@gototagsdev ID's shouldn't matter, I'm filtering on level greater than 1. Judging from your screenshots, this should exclude the Default Category (with ID 2 and level 1). Are you sure you're using the latest version?
