### ISSUE TITLE
Category Path Generation Randomly Skips Categories

### ISSUE THREAD

**Issue by johnjosephson** [elgentos/regenerate-catalog-urls#21]
Nice module, helpful.
I have not had a chance to debug why regenerating url_path is not working for some categories. We have 2000 categories. Running different times resulted in different categories not being generated. My theory is that mt_rand(0,1000) sometimes returns "0" which is failing some test. I replaced that with mt_rand(1,1000) + time() [for good measure] and the problem went away.

**Comment by peterjaap** [comment]
Hi @johnjosephson where did you change that? There is no `mt_rand()` call in this extension?

**Comment by johnjosephson** [comment]
https://github.com/elgentos/regenerate-catalog-urls/blob/master/Iazel/RegenProductUrl/Console/Command/RegenerateCategoryPathCommand.php

Line 132/133

**Comment by peterjaap** [comment]
Ok Github search was apparently failing me. That is a very obscure and infrequently occurring bug, great find! 

I changed the code and did a new release.
