### ISSUE TITLE
Url generation for invisible products

### ISSUE THREAD

**Issue by GordonLesti** [elgentos/regenerate-catalog-urls#30]
Dear Elegantos-Team,
it's seems that urls will be generated also for simple products that are not visible individually. Would you accept a pull request to filter those products?

Best Regards
Gordon

**Comment by peterjaap** [comment]
Apparently, I already did that, but maybe I missed something? https://github.com/elgentos/regenerate-catalog-urls/commit/3b8c8183623f62dc9b61fbd1b710eb88979f6dca

**Comment by GordonLesti** [comment]
Hello @peterjaap ,
yes, looks like. I will double check and get back to you. Thanks for your fast response.

Beste Regards
Gordon
