### ISSUE TITLE
Duplicated products urls

### ISSUE THREAD

**Issue by samyscoub** [elgentos/regenerate-catalog-urls#32]
Hello I've this kind of errors when I ued your module : 

```shell
php bin/magento regenerate:product:url
...
Duplicated url for store ID 1, product 2418 (REN420M-C3RS) - URL key for specified store already exists. Generated URLs
```
Can you tell me what to do for this kind of products ?

Regards

**Comment by peterjaap** [comment]
What do you mean with "this kind of products"? What kind of product is it?

**Comment by peterjaap** [comment]
@samyscoub oh I see now, that error has nothing to do with this extension. You have duplicate URL key values within a storeview in `catalog_product_entity_varchar`. You can use this extension to check those (and you need to fix them manually): https://github.com/baldwin-agency/magento2-module-url-data-integrity-checker

**Comment by perryholden** [comment]
A custom `url_rewrite` entry for that product's URL key can also cause this.
