### ISSUE TITLE
Problem regenerating product url 

### ISSUE THREAD

**Issue by puntable** [elgentos/regenerate-catalog-urls#35]
I had some conflicts between some product URL's. I copied product and somehow this created dublicate URL's in DB.

Now i have manually deleted all rows of one specific product (id: 23876) in table `url_rewrite`, but for some reason when i do `php bin/magento regenerate:product:url 23876` it doesn't regenerate URL's. It seems like it cant find the product?
Output is: `Done regenerating. Regenerated 0 urls for store Default Store View`
It seems to be default output, when the specified product ID doesn't exists..

Any idea why this is happening?

**Comment by peterjaap** [comment]
Can't really say, but you should check whether the product exists, is attached to the default store or is otherwise lacking some information. Maybe it's not active in the current store? etc

**Comment by peterjaap** [comment]
Closed due to inactivity.
