### ISSUE TITLE
URL's not regenerating

### ISSUE THREAD

**Issue by mtjweb** [elgentos/regenerate-catalog-urls#36]
I installed the module via composer on Magento 2.3.5-p1.

Ran the following commands:
composer require elgentos/regenerate-catalog-urls
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy nl_NL de_DE fr_FR en_US
php bin/magento regenerate:product:url

Got a list of messages that url's were regenerated. After that I reindexed and emptied the cache.

When I checked in admin, the old url's were still in place.

**Comment by peterjaap** [comment]
And what happens when you delete all system urls and try again? Are they
generated or not? If they are, are they the same as before? In that case,
the problem lies elsewhere.

**Comment by mtjweb** [comment]
When I delete the url in admin and I save the product, it is regenerated. Or do you want me to delete them in the database?

**Comment by peterjaap** [comment]
Delete them from the database and run the console command

**Comment by jorgb90** [comment]
I have the same problem. Urls are not regenerating in 2.3.5-p1. At least not through the action in the product grid.

**Comment by peterjaap** [comment]
@jorgb90 and when run from the console?

**Comment by peterjaap** [comment]
Closed due to inactivity.
