### ISSUE TITLE
Multiple Categories in 2.3.5-p1

### ISSUE THREAD

**Issue by WebKenth** [elgentos/regenerate-catalog-urls#38]
https://github.com/elgentos/regenerate-catalog-urls/blob/14bb8cefda1dd5054432e4da1f266f23d5565847/Iazel/RegenProductUrl/Console/Command/RegenerateCategoryPathCommand.php#L125

If you give the command multiple identifiers it's expected that it would process more of them

Given:
```
bin/magento regenerate:category:path "23847,23848,23849,23850,23851,23852,23853,23854,23855,23856,23857,23858,23859,23860,23861,23862,23863,23864,23865,23866,23867,23868,23869,23870,23871,23872,23873,23874,23875,23876,23877,23878,23879,23880,23881,23882,23883,23884,23885,23886,23887,23888,23889,23890,23891,23892,23893,23894,23895,23896,23897,23898,23899,23900,23901,23902,23903,23904,23905,23906,23907,23908,23909,23910,23911,23912,23913,23914,23915,23916,23917,23918,23919,23920,23921,23922,23923,23924,23925,23926,23927,23928,23929,23930,23931,23932,23933,23934,23935,23936,23937,23938,23939,23940,23941,23942,23943,23944,23945,23946" -s 0
``` 

```
        if (!empty($cids)) {
            $categories->addAttributeToFilter('entity_id', ['in' => $cids]);
        }
```
Outputs: 
`var_dump($categories->count())` => `1`

addAttributeToFilter `in` filter expects an array, not a comma serperated string 
( excuse the ugly array accessor, there's probably a better way ) 
```
        if (!empty($cids)) {
            $cids = explode(',', $cids[0]);
            $categories->addAttributeToFilter('entity_id', ['in' => $cids]);
        }
```
Outputs: 
`var_dump($categories->count())` => `100`

**Comment by peterjaap** [comment]
@WebKenth you should pass it with spaces, and without the quotes. Then the Symfony Console component will automatically make it an array. See https://github.com/elgentos/regenerate-catalog-urls#how-to-use
