### ISSUE TITLE
 elgentos/regenerate-catalog-urls 0.2.9 requires magento/module-url-rewrite ^102.0 

### ISSUE THREAD

**Issue by shinesoftware** [elgentos/regenerate-catalog-urls#46]
Hello,

why I get this error?

![Selection_441](https://user-images.githubusercontent.com/1553035/127138303-82eee5d3-5359-42f2-a354-00ba461a812e.jpg)

thanks

**Comment by peterjaap** [comment]
You're right, the constraints on the modules were too strict. I've created a new release https://github.com/elgentos/regenerate-catalog-urls/releases/tag/0.2.10

**Comment by shinesoftware** [comment]
Hello @peterjaap thanks for the fast resolution of the issue! 
I have just updated the extension and now it works! 
Thanks again
