### ISSUE TITLE
Feature-Request: Execute command for all store views

### ISSUE THREAD

**Issue by amenk** [elgentos/regenerate-catalog-urls#49]
Omitting the "-s" Option regenerates only for Store 0 - it would be conventient to have a "-s all" option, or is this already possible?

**Comment by peterjaap** [comment]
No not yet, that is indeed an omission.

**Comment by peterjaap** [comment]
Done; https://github.com/elgentos/regenerate-catalog-urls/commit/9cb009648b1d60f57f3efd4c2447d81880f01db7

**Comment by amenk** [comment]
Thank you @peterjaap

**Comment by amenk** [comment]
Should be added to the readme as well ;-)
