### ISSUE TITLE
Put it on packagist

### ISSUE THREAD

**Issue by amenk** [elgentos/regenerate-catalog-urls#6]
As the old module is deprecated, this should be properly published :-)

**Comment by peterjaap** [comment]
Well the package already exists ofcouse; `A package with the name iazel/module-regen-product-url already exists.`.

What would you suggest we do? Rename this one and submit it?

**Comment by amenk** [comment]
Yes, as the other one is deprecated, I would suggest a rename

**Comment by peterjaap** [comment]
I've renamed it to `elgentos/regenerate-catalog-urls` and submitted it; https://packagist.org/packages/elgentos/regenerate-catalog-urls
