### ISSUE TITLE
Stable version

### ISSUE THREAD

**Issue by flancer64** [elgentos/regenerate-catalog-urls#8]
Hi, @peterjaap . 

Thanks for the further development of the "Iazel/magento2-regenurl" module. Could you create first release for the module on Github?

I need to
```
$ composer require elgentos/regenerate-catalog-urls:"dev-master as 0.1.0"
```

if `minimum-stability` is not `dev` in head project's `composer.json`.

Thanks,

Alex.

**Comment by peterjaap** [comment]
Done

https://github.com/elgentos/regenerate-catalog-urls/releases/tag/0.1.0

**Comment by flancer64** [comment]
Thanks :+1:
